spring.application.name=ecsite

# PostgreSQL JDBCドライバーの指定
spring.datasource.driver-class-name=org.postgresql.Driver

# 接続URL（データベース名を my_database に変更してください）
spring.datasource.url=jdbc:postgresql://localhost:5432/ecsite

# データベースのユーザー名とパスワード
spring.datasource.username=ecsite
spring.datasource.password=ecsite


logging.level.org.mybatis=DEBUG
logging.level.java.sql.PreparedStatement=DEBUG
logging.level.jp.co.ecsite.dao=DEBUG